name: Deploying backend to the server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Navigate to your project directory
          cd /var/www/backgroundchecker-backend

          # Pull the latest changes
          git pull origin main

          # Set proper permissions (adjust as needed)
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .

          # Restart Apache to apply changes
          sudo systemctl restart apache2

          # Optionally, clear PHP opcode cache
          sudo service php8.3-fpm reload
